### ISSUE TITLE
workerpool: add ability to stop new work from queuing

### ISSUE THREAD

**Issue by sethvargo** [abcxyz/pkg#147]
### TL;DR

Developers should be able to stop execution of future queued work.

### Detailed design

```markdown
We could possibly return a sentinel error or just stop the worker.
```

**Comment by sethvargo** [comment]
@dcreey I see a few design options here:

### context-based

This is somewhat how contexts are intended to be used:

```go
ctx, cancel := context.WithCancel(context.Background())
defer cancel()

pool.Do(ctx, func() (string, error) {
  result, err := something()
  if err != nil {
    defer cancel() // stop future invocations
    return err
  }
})
```

With the current API, this will work, but each future call to `Do` will return `ContextCancelled`.

### stop-based

This also works today:

```go
pool.Do(ctx, func() (string, error) {
  result, err := something()
  if err != nil {
    defer pool.Done(context.Background()) // stop future invocations
    return err
  }
})
```

With the current API, this will work, but each future call to `Do` will return `ErrStopped`.

### Wrapped concrete error

This one feels the least intuitive and too magical for me:

```go
pool.Do(ctx, func() (string, error) {
  result, err := something()
  if err != nil {
    return fmt.Errorf("%w: failed to thing: %w", ErrHalt, err)
  }
})
```

where `ErrHalt` is a magical sentinel error.

### Other

I don't want a generic configurable like "StopOnError" because it's too coarse. You might want to stop on certain errors but continue on others. Then you start down the slippery slope of allowlist/denylist errors, and it feels easier just to require a specific call in the function body to terminate.

**Comment by sethvargo** [comment]
@drevell for his thoughts too

**Comment by drevell** [comment]
My non-binding thoughts:

# Thought number 1

- These two use cases might be different enough to have separate APIs:
    - Case 1: "Run indefinitely with error tolerance," like a server.
    - Case 2: "I have a finite list of things to do, like HTTP gets, and want it to be fast so I'm doing it concurrently." Batch stuff.

For use case 1, context cancellation (or pool.Done()) makes good sense to me.

For use case 2, context cancellation (or pool.Done()) would work but it seems to me like it doesn't hit the API design sweet spot of "there's a single obvious way to do it." You have to know about the special errors returned from pool.Do(). You have to gather your own errors using a channel or something, without any common channel mistakes like accidentally blocking something important. You have to have read the docs about context cancellation.

For case 2, maybe we can provide a separate pool type that has a `DoUntilError` method that takes an `ErrWorker func(T) error`? This could be built on top of the other pool, I think.

## Thought number 2

Maybe we're swimming against the tide here by not using sourcegraph/conc, even though it's not ideal.

## Thought number 3

> You might want to stop on certain errors but continue on others

There could be a config option with a callback like `IsHaltableError(error) bool`. Still a bit clunky though.

**Comment by dcreey** [comment]
Piggy backing off of what @drevell said.

### Thought number 1
I agree with Dave here. Its two explicit use cases. We can support both with a single api but it means greater complexity for the author, reviewer, and future reviewer.

### Thought number 2
I prefer this over the context cancel since context cancel might not cancel all work if you have multiple contexts

### Thought number 3
Too much complexity IMO. 

### Thought number 4 (other)
Honestly I think I like this one the most. The caller already has the option of whether or not to return an error. If they want to decide to ignore certain errors they can have error type checking in their func and decide to retry, ignore, return. And in fact, they could wrap their func with another func that handles retry/ignore. Seems fairly straightforward and leaves the user thinking about their application logic instead of the pool logic. 

Additionally, I think this solves for the majority of the batch use case. The use case where someone is doing batch and wants to ignore some errors and do nothing (return the error but not retry and not cancel) seems more like an edge case. And in this scenario they can always fallback to using approach 1 or 2.

I'm a big fan of less LOC and less for the reader to think about. Forcing the user to cancel on error means that the user needs to consider the intent of the cancel - is this a special type of error we are cancelling on or are we just trying to cancel generally? In the latter case did the author remember to cancel correctly in all funcs?

**Comment by sethvargo** [comment]
This was fixed in https://github.com/abcxyz/pkg/pull/156
